Gstpe 36: Rest Module
belnogs/GSE-OnBoarding-Back-end pull request #3
Opened 2022-05-27 20:32 UTC by belnogs

https://liferay.atlassian.net/browse/GSTPE-36

2022-05-30 13:14 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-rest/amf-registration-rest-impl/rest-openapi.yaml
> +                        Who is your favorite actor?
Please, change description for something more succinct. the question might change in future, for instance.

2022-05-30 13:25 UTC, belnogs commented on modules/amf-registration/amf-registration-rest/amf-registration-rest-impl/rest-openapi.yaml
> +                        Who is your favorite actor?
Done

2022-06-01 11:49 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-rest/amf-registration-rest-impl/src/main/java/com/liferay/amf/internal/resource/v1_0/AccountResourceImpl.java
> +	}
you should call the `AccountLocalService` (the one you've created) and their CRUD methods respectively for each method defined in `AccountResourceImpl`. for that, you might need to include the `account-api` as a dependency in your `build.gradle` file. then, add something like this to call the service methods:

```
@Reference
private AccountLocalService _accountLocalService;
```

let me know if you have any other questions ;)

2022-06-15 12:01 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-service/service.xml
> +		<column name="accountId" primary="true" type="String" />
it is a best practice to use `long` for Ids

2022-06-15 12:03 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-rest/amf-registration-rest-impl/src/main/java/com/liferay/amf/internal/resource/v1_0/AccountResourceImpl.java
> +		return (Account) _accountLocalService.getAccount(accountId);
casting types might lead to errors. I would recommend to create a `mapper` class and include within it a `toDTO` method to convert `Account` (model) to `Account` (DTO).

2022-06-15 12:03 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-rest/amf-registration-rest-impl/src/main/java/com/liferay/amf/internal/resource/v1_0/AccountResourceImpl.java
> +		return (Account) _accountLocalService.createAccount(account.getFirstName(), account.getLastName(),
same as above.

2022-06-15 12:03 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-rest/amf-registration-rest-impl/src/main/java/com/liferay/amf/internal/resource/v1_0/AccountResourceImpl.java
> +		return (Account) _accountLocalService.updateAccount(accountId, account.getFirstName(), account.getLastName(),
same as above.

2022-06-15 12:05 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-rest/amf-registration-rest-impl/src/main/java/com/liferay/amf/rest/internal/resource/v1_0/AccountResourceImpl.java
> +		return account;
use the `mapper` class to convert the `Account` (model) to `Account` (DTO) and return this last one. so we make sure everything was assigned and returned properly (my opinion).

2022-06-15 12:06 UTC, alexandresjunior requested changes
Added a few more comments. Let me know if you have any more questions, thanks!  ;)

2022-06-15 18:39 UTC, isabelanog commented
GSTPE-36: Rest Module Review

2022-06-16 18:15 UTC, merged