GSTPE 48 - Web module
belnogs/GSE-OnBoarding-Back-end pull request #4
Opened 2022-06-08 17:17 UTC by belnogs

https://liferay.atlassian.net/browse/GSTPE-34

2022-06-15 12:09 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-service/service.xml
> +		<column name="birthday" type="String" />
you can use a `Date` variable instead of `String`. you can convert it using a `parse` function.

2022-06-15 12:13 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-web/src/main/java/com/liferay/amf/web/actions/RegisterAccountMVCActionCommand.java
> +      System.out.println("Account created sucefully");
fix typo and please remove any logs in console. if u want to lunch any logs, you can use something like this instead:

```
_log.info("Account created successfully");

[...]

private static final Log _log = LogFactoryUtil.get(NameOfTheClass.class.getName());
```

2022-06-15 12:14 UTC, alexandresjunior requested changes
looks good to me, congrats! I've added a few comments, though. let me know if you have any questions ;)

2022-06-15 18:49 UTC, belnogs commented
GSTPE-48 Review

2022-06-16 18:17 UTC, alexandresjunior commented on modules/amf-registration/amf-registration-service/service.xml
> +		<column name="birthday" type="Date" />
make sure to run `buildService` again so changes take effect in the service classes.

2022-06-16 18:19 UTC, alexandresjunior commented
as #3 has been deployed, please rebase this branch with main branch and force push your commits to remote.
you can use those git commands for that:

```
git pull --rebase origin main
git push origin +GSTPE-48
```

2022-06-20 11:36 UTC, alexandresjunior commented
@belnogs I still see conflict with main branch. did you rebase this branch with it?

2022-06-21 12:09 UTC, merged